-- 1. Tabel Transaksi (Data Mentah Toko)
-- Di dunia nyata, ini mungkin database terpisah. Di sini kita pisahkan pakai 'store_id'.
create table transactions (
  id bigint generated by default as identity primary key,
  store_id text not null, -- 'TOKO_A' atau 'TOKO_B'
  menu_item text not null,
  amount int not null,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. Tabel Requests (Perintah dari Master)
create table command_requests (
  request_id uuid default gen_random_uuid() primary key,
  command_type text not null, -- misal: 'GET_REVENUE'
  payload jsonb, -- parameter, misal: { "menu": "Nasi Goreng" }
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 3. Tabel Results (Jawaban dari Toko)
create table command_results (
  id bigint generated by default as identity primary key,
  request_id uuid references command_requests(request_id),
  store_id text not null,
  result_data jsonb, -- Hasil hitungan, misal: { "total": 500000 }
  created_at timestamp with time zone default timezone('utc'::text, now())
);